name: Feature Request
description: Request a new feature.
title: "[Feature Request] "
labels: ["enhancement"]
assignees:
  - ggjorven
type: feature
body:
  - type: textarea
    id: feature-request
    attributes:
      label: Requested feature
      description: New feature description.
      placeholder: Tell us your amazing idea!
      value: "My amazing feature idea is ...!"
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: How to implement
      description: If applicable, how to implement this feature.
      placeholder: Steps to implement this feature.
      value: "1. Step 1..."
    validations:
      required: false
  - type: textarea
    id: issues
    attributes:
      label: Relevant issues
      description: Any issues that could be solved with this feature
    validations:
      required: false
