name: Rust

on:
  push:
    branches: [ "main", "dev", "feature/**", "fix/**" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint-codeql:
    name: Lint (CodeQL)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: rust
        build-mode: none

    - name: Analyze code
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:actions"

  lint-clippy:
    name: Lint (Clippy)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install clippy
        run: cargo install clippy-sarif sarif-fmt

      - name: Run clippy
        id: lint-job
        run: |
          cargo clippy \
            --all-features \
            --message-format=json \
            | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
          exit ${PIPESTATUS[0]}
        continue-on-error: true

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

      - name: Fail on lint error
        if: steps.lint-job.outcome == 'failure'
        run: exit 1

  lint-rustfmt:
    name: Lint (Rustfmt)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CARGO_TERM_COLOR: always
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CARGO_TERM_COLOR: always
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests
      run: cargo test --verbose
